### ISSUE TITLE
DirTNT 1.4-120.2 Deadlocks @ Mojang loading Screen -IF- Continuity 3.0.0b4-120.2 is present.

### ISSUE THREAD

**Issue by Tursiops-G** [Fourmisain/DirTNT#5]
1.20.2 (Fabric loader 0.14.23)
Verified w/ Test Instance:
brrp-fabric-1.0.2-1.20.2.jar
continuity-3.0.0-beta.4+1.20.2.jar
DirTNT-1.4-1.20.2.jar
fabric-api-0.90.0+1.20.2.jar
No other mods installed,

No Crash, Have to manually kill process.

Run Log:
https://paste.ee/p/3m3pr

Latest Log:
https://paste.ee/p/ckitZ

**Comment by Fourmisain** [comment]
Hm... I'm not sure if I can fix this on my end.
My current issue is that Continuity's source code is not up-to-date. The last source is only for 1.19.2 and there were massive texture stitching changes in 1.19.3 and some in 1.20.2 too, so I can't easily debug the issue.

It looks like there could be an easy compatibility fix on Continuity's side though, so I'll try reporting it.

**Comment by Tursiops-G** [comment]
Thanks. Hope it's an easy fix for them.
LOVE this Mod!... It's making in-world, Non-Creative terrain construction a whole lot easier... :) 👍

**Comment by Fourmisain** [comment]
After a month of thinking, I thought I had a solution, but it ultimately ran into the same issues I originally had when I rewrote the stitching code thrice.

Now I looked at it again and found a super simple fix for the issue!
![solved](https://github.com/Fourmisain/DirTNT/assets/8464472/e3962525-4b69-43ec-89a1-86db50d2aca6)

New release is ready!
