### ISSUE TITLE
All fonts turned to rectangles

### ISSUE THREAD

**Issue by darkqueen1229** [Fourmisain/DirTNT#6]
Is there any known compatibility issues that cause all text to change to just rectangles? I've looked at previous issues and I don't see my issue or a solution to it in any of them. I have several mods installed but have narrowed it down to an issue with DirtTNT and another mod but haven't figured out the other mod yet.

**Comment by Fourmisain** [comment]
What Minecraft version are you on?

It is very well possible there's a mod conflict with mods that generate textures like Continuity, as this mod generates all TNT textures with admitedly less than optimal texture stitching mixins.
I'll recheck Continuity, it's possible the old compatibility workaround broke.
**edit**: At least on 1.20.6 Continuity 3.0.0-beta.5 works fine together with DirTNT.

Are there any errors in the latest.log? Can you send your narrowed down mod list (or the log file)?

**Comment by darkqueen1229** [comment]
It is indeed Continuity.

Running MC 1.20.1 with Continuity 3.0.0-beta.4+1.20.1 & DirTNT 1.4-1.20.

**Comment by Fourmisain** [comment]
Aha, the compatibility code needed a backport!
New versions for 1.19.4 and 1.20(.1) are out!

**Comment by darkqueen1229** [comment]
Thank you! I appreciate that so very much. :D
